"""init

Revision ID: 328289d9d1c0
Revises: 00c7f2948078
Create Date: 2023-08-20 14:18:32.885207

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "328289d9d1c0"
down_revision: Union[str, None] = "00c7f2948078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats", "foreword", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.create_unique_constraint(None, "chats", ["foreword"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chats", type_="unique")
    op.alter_column(
        "chats",
        "foreword",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    # ### end Alembic commands ###
