"""add timezone to message_datetime

Revision ID: 3dafabf91dda
Revises: b425cf0b90e6
Create Date: 2023-08-21 03:07:17.532836

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3dafabf91dda"
down_revision: Union[str, None] = "b425cf0b90e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
