"""add to chats new column - interval

Revision ID: 47b1eb23cf03
Revises: 84af4dad15e6
Create Date: 2023-08-22 21:01:42.491816

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "47b1eb23cf03"
down_revision: Union[str, None] = "84af4dad15e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats", sa.Column("interval", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "interval")
    # ### end Alembic commands ###
