"""insest new column 'message_time' in chats

Revision ID: 80d89ccca571
Revises: faceae81c551
Create Date: 2023-08-21 02:10:36.093337

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "80d89ccca571"
down_revision: Union[str, None] = "faceae81c551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("message_date", sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "message_date")
    # ### end Alembic commands ###
