"""unique fallse in nickname and foreword

Revision ID: 84af4dad15e6
Revises: 3dafabf91dda
Create Date: 2023-08-21 23:46:31.533119

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "84af4dad15e6"
down_revision: Union[str, None] = "3dafabf91dda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chats_foreword_key", "chats", type_="unique")
    op.drop_constraint("chats_nickname_key", "chats", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("chats_nickname_key", "chats", ["nickname"])
    op.create_unique_constraint("chats_foreword_key", "chats", ["foreword"])
    # ### end Alembic commands ###
