"""insest new column in chats

Revision ID: faceae81c551
Revises: b816d92a72b6
Create Date: 2023-08-21 01:47:23.240978

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "faceae81c551"
down_revision: Union[str, None] = "b816d92a72b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("message_time", sa.DATE(), nullable=True))
    op.create_unique_constraint(None, "schedulers", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedulers", type_="unique")
    op.drop_column("chats", "message_time")
    # ### end Alembic commands ###
